// SPDX-License-Identifier: UNLICENSED
pragma solidity 0.8.28;

/// @title IHonkVerifier
/// @notice Interface for UltraHonk ZK proof verifier.
/// @dev Implementation auto-generated by Aztec Barretenberg (bb write_solidity_verifier)
///      from the Noir circuit. Swappable via setHonkVerifier in EnergyProofRegistryV3
///      (e.g., when migrating from v06 → v08 ZK schema in Etap 3).
///      Hash function inside circuit: Poseidon (decision committed 2026-05-12).
interface IHonkVerifier {
    function verify(
        bytes calldata proof,
        bytes32[] calldata publicInputs
    ) external view returns (bool);
}
