/**
 * V3 chain client — submitProof caller via viem.
 *
 * Spec: docs/specs/aggregator_design.md §3.3.
 * ABI source: src/chain/abi.ts (auto-generated by scripts/generate-abi.ts).
 *
 * Submission flow:
 *   1. simulateContract — catches reverts WITHOUT burning gas. Returns the
 *      decoded V3 custom error if check fails (e.g. DeviceNotActive,
 *      InvalidZKProof) so we can route to retry/quarantine appropriately.
 *   2. writeContract — only if simulation succeeded. Aggregator signs with
 *      OPERATOR_ROLE private key.
 *   3. waitForTransactionReceipt — confirm inclusion + check status.
 *
 * Cost: simulation is free (eth_call). writeContract = real gas (~500k for
 * full verify chain per V3 design §15).
 */

import {
  createWalletClient,
  createPublicClient,
  http,
  type Address,
  type Hash,
  type Hex,
  type Account,
} from "viem";
import { privateKeyToAccount } from "viem/accounts";
import { sepolia } from "viem/chains";
import { V3_ABI } from "./abi.js";
import { computeTotalEnergy } from "../prover/witness.js";
import type { HonkProof } from "../prover/honk.js";
import type { CanonicalPayload } from "../verify/canonical.js";

// ---------- Types ----------

export interface SubmissionInputs {
  payload: CanonicalPayload;
  /** 32-byte payload hash (edge signed this). */
  payloadHash: Uint8Array;
  /** 64-byte P-256 signature (r || s, low-s normalized). */
  signature: Uint8Array;
  /** 64-byte uncompressed P-256 public key (X || Y, no 0x04 prefix). */
  devicePubkey: Uint8Array;
  proof: HonkProof;
}

export interface SubmissionResult {
  txHash: Hash;
  blockNumber: bigint;
  gasUsed: bigint;
}

export interface ChainClientConfig {
  /** EnergyProofRegistryV3 proxy address. */
  v3Address: Address;
  /** RPC URL (Alchemy / Infura / self-hosted). */
  rpcUrl: string;
  /** Operator private key (0x-prefixed hex). Must have OPERATOR_ROLE on V3. */
  operatorPrivateKey: Hex;
}

// V3 custom errors plus the OZ ones submitProof can produce.
// Routing intent for each:
//   retry-able:        EpochInFuture (clock skew), EnforcedPause (admin lifted)
//   quarantine:        InvalidP256Signature, InvalidZKProof, PayloadHashMismatch (bad data)
//   never-retry:       SessionKeyAlreadyUsed (already submitted), DeviceNotActive
//   misconfiguration:  AccessControlUnauthorizedAccount (operator key wrong)
//   protocol bug:      ReentrancyGuardReentrantCall (should not happen)
export type ChainErrorCode =
  | "DeviceNotActive"
  | "InvalidP256Signature"
  | "PayloadHashMismatch"
  | "InvalidZKProof"
  | "SessionKeyAlreadyUsed"
  | "EpochInFuture"
  | "InvalidTimestamp"
  | "InvalidPubkeyLength"
  | "InvalidSignatureLength"
  | "AccessControlUnauthorizedAccount"
  | "EnforcedPause"
  | "ReentrancyGuardReentrantCall"
  | "TX_REVERTED"
  | "UNKNOWN";

const KNOWN_ERROR_NAMES = new Set<string>([
  "DeviceNotActive",
  "InvalidP256Signature",
  "PayloadHashMismatch",
  "InvalidZKProof",
  "SessionKeyAlreadyUsed",
  "EpochInFuture",
  "InvalidTimestamp",
  "InvalidPubkeyLength",
  "InvalidSignatureLength",
  "AccessControlUnauthorizedAccount",
  "EnforcedPause",
  "ReentrancyGuardReentrantCall",
]);

export class ChainSubmissionError extends Error {
  constructor(
    public readonly code: ChainErrorCode,
    message: string,
    public readonly txHash?: Hash,
  ) {
    super(message);
    this.name = "ChainSubmissionError";
  }
}

// ---------- Client ----------

export class V3ChainClient {
  private readonly publicClient: ReturnType<typeof createPublicClient>;
  private readonly walletClient: ReturnType<typeof createWalletClient>;
  private readonly account: Account;
  private readonly v3Address: Address;

  constructor(config: ChainClientConfig) {
    this.account = privateKeyToAccount(config.operatorPrivateKey);
    this.v3Address = config.v3Address;
    this.publicClient = createPublicClient({
      chain: sepolia,
      transport: http(config.rpcUrl),
    });
    this.walletClient = createWalletClient({
      chain: sepolia,
      transport: http(config.rpcUrl),
      account: this.account,
    });
  }

  /** Operator address (derived from private key). */
  get operatorAddress(): Address {
    return this.account.address;
  }

  /**
   * Submit a proof to V3.submitProof.
   *
   * @throws ChainSubmissionError with discriminated `code` for routing.
   */
  async submitProof(inputs: SubmissionInputs): Promise<SubmissionResult> {
    const payloadHashHex = bytesToHex(inputs.payloadHash);
    const signatureHex = bytesToHex(inputs.signature);
    const devicePubkeyHex = bytesToHex(inputs.devicePubkey);
    const proofHex = bytesToHex(inputs.proof.proof);

    const pubInputs = {
      deviceId: inputs.payload.device_id,
      sessionId: inputs.payload.session_id,
      epochStartTs: inputs.payload.epoch_start_ts,
      lat_e7: inputs.payload.lat_e7,
      lon_e7: inputs.payload.lon_e7,
      lightLevel: inputs.payload.light_level,
      tamperFlag: inputs.payload.tamper_flag,
      payloadHash: payloadHashHex,
      totalEnergyMWh: computeTotalEnergy(inputs.payload),
    } as const;

    const args = [
      pubInputs,
      payloadHashHex,
      signatureHex,
      devicePubkeyHex,
      proofHex,
    ] as const;

    // Simulate first — free pre-flight check that returns decoded revert
    try {
      await this.publicClient.simulateContract({
        address: this.v3Address,
        abi: V3_ABI,
        functionName: "submitProof",
        args,
        account: this.account,
      });
    } catch (err) {
      throw mapChainError(err);
    }

    // Simulation passed — submit real tx
    let txHash: Hash;
    try {
      txHash = await this.walletClient.writeContract({
        address: this.v3Address,
        abi: V3_ABI,
        functionName: "submitProof",
        args,
        chain: sepolia,
        account: this.account,
      });
    } catch (err) {
      throw mapChainError(err);
    }

    const receipt = await this.publicClient.waitForTransactionReceipt({
      hash: txHash,
    });
    if (receipt.status !== "success") {
      throw new ChainSubmissionError(
        "TX_REVERTED",
        `Transaction ${txHash} reverted after inclusion (chain reorg or condition changed between simulate and write)`,
        txHash,
      );
    }
    return {
      txHash,
      blockNumber: receipt.blockNumber,
      gasUsed: receipt.gasUsed,
    };
  }
}

// ---------- Helpers ----------

function bytesToHex(bytes: Uint8Array): Hex {
  let h = "0x";
  for (const b of bytes) h += b.toString(16).padStart(2, "0");
  return h as Hex;
}

/**
 * Map viem revert errors to ChainSubmissionError with discriminated code.
 *
 * viem nests decoded revert in `cause.data.errorName` for ContractFunctionExecutionError.
 * If error name is not in our known set (e.g. RPC failure, network) — returns UNKNOWN.
 */
function mapChainError(err: unknown): ChainSubmissionError {
  const anyErr = err as {
    cause?: { data?: { errorName?: string } };
    data?: { errorName?: string };
    errorName?: string;
    shortMessage?: string;
    message?: string;
  };
  const errorName =
    anyErr?.cause?.data?.errorName ??
    anyErr?.data?.errorName ??
    anyErr?.errorName;
  if (errorName && KNOWN_ERROR_NAMES.has(errorName)) {
    return new ChainSubmissionError(
      errorName as ChainErrorCode,
      `V3 revert: ${errorName}`,
    );
  }
  const msg = anyErr?.shortMessage ?? anyErr?.message ?? String(err);
  return new ChainSubmissionError("UNKNOWN", msg);
}
